
name = "personal-site"
main = "spotify-worker.js"
compatibility_date = "2024-01-30"

[build]
command = "npm run build"
cwd = "."
watch_dir = "src"

[site]
bucket = "./build"
pages_build_output_dir = "./build"

[env.production]
name = "personal-site"
vars = { ENVIRONMENT = "production" }
routes = ["personal-site.pages.dev/*"]

[env.development]
name = "personal-site-dev"
vars = { ENVIRONMENT = "development" }

[[rules]]
type = "CompiledWasm"
globs = ["**/*.wasm"]

[[rules]]
type = "Text"
globs = ["**/*.html", "**/*.css", "**/*.js", "**/*.json"]
