name = "personal-site"
main = "spotify-worker.js"
compatibility_date = "2024-01-30"

[build]
command = "npm run build"
watch_dir = "build"

[site]
bucket = "./build"

[env.production]
name = "personal-site"
vars = { ENVIRONMENT = "production" }

[env.development]
name = "personal-site-dev"
vars = { ENVIRONMENT = "development" }