me = "personal-site"
main = "src/worker/index.ts"
compatibility_date = "2024-02-01"

[build]
command = "npm run build"  # Changed from build:worker to build

[env.production]
name = "personal-site"
vars = { ENVIRONMENT = "production" }

[env.development]
name = "personal-site-dev"
vars = { ENVIRONMENT = "development" }

[dev]
port = 8787

# Exclude files and directories from deployment
[site]
bucket = "./dist"  # Output directory
exclude = [".unused/**/*"]  # Exclude .unused directory
