name = "personal-site"
main = "src/worker/index.ts"
compatibility_date = "2024-02-01"

[build]
command = "npm run build:worker"

[env.production]
name = "personal-site"
vars = { ENVIRONMENT = "production" }

[env.development]
name = "personal-site-dev"
vars = { ENVIRONMENT = "development" }

[dev]
port = 8787
