name = "personal-site"
main = "spotify-worker.js"
compatibility_date = "2024-02-01"

[build]
command = "npm run build"
watch_dir = "src"

[site]
bucket = "./dist"

[env.production]
name = "personal-site"
routes = ["personal-site.pages.dev/*"]
vars = { ENVIRONMENT = "production" }

[env.development]
name = "personal-site-dev"
vars = { ENVIRONMENT = "development" }

[vars]
ENVIRONMENT = "development"
